#ifndef _TERMINAL_CONTROL_CONSTANTS_H_
#define _TERMINAL_CONTROL_CONSTANTS_H_

#define CONTROL_GPIO_READ 0x01
#define CONTROL_GPIO_WRTIE 0x02
#define CONTROL_CODE_EXEC 0x03
#define DATA_GPIO_READ 0x01
#define DATA_CODE_EXEC 0x03

#ifndef MAX_VMS
#define MAX_VMS 16
#endif

#endif
