#ifndef _TERMINAL_CONTROL_HYPERCALLS_H_
#define _TERMINAL_CONTROL_HYPERCALLS_H_

#define HC_IO_DIGITAL_READ 0x01
#define HC_IO_DIGITAL_WRITE 0x02
#define HC_IO_SET_PIN_MODE 0x03
#define HC_IO_ANALOG_READ 0x04
#define HC_IO_ANALOG_WRITE 0x05
#define HC_DEVICE_RESET 0x06
#define HC_DEVICE_CLOCK_READ 0x07

#endif
